version: "3"

services:
    db:
        build: ./.docker/mysql
        container_name: db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=code_logzz
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: redis
        networks:
        - app-network
        ports:
        - "6379:6379"

networks:
    app-network:
        driver: bridge
